/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.7.4-338
 *
 */
import { Fluence, FluencePeer } from '@fluencelabs/fluence';
import {
    CallParams,
    callFunction,
    registerService,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v3';


// Services

export interface ImageGeneratorDef {
    mergedSpriteImages: (metadata: string, callParams: CallParams<'metadata'>) => string | Promise<string>;
    readMetadata: (tokenURI: string, callParams: CallParams<'tokenURI'>) => string | Promise<string>;
    readTokenURI: (tokenAddress: string, tokenId: number, callParams: CallParams<'tokenAddress' | 'tokenId'>) => string | Promise<string>;
}
export function registerImageGenerator(service: ImageGeneratorDef): void;
export function registerImageGenerator(serviceId: string, service: ImageGeneratorDef): void;
export function registerImageGenerator(peer: FluencePeer, service: ImageGeneratorDef): void;
export function registerImageGenerator(peer: FluencePeer, serviceId: string, service: ImageGeneratorDef): void;
       

export function registerImageGenerator(...args: any) {
    registerService(
        args,
        {
    "defaultServiceId" : "imageGenerator",
    "functions" : {
        "tag" : "labeledProduct",
        "fields" : {
            "mergedSpriteImages" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "metadata" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    ]
                }
            },
            "readMetadata" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "tokenURI" : {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    ]
                }
            },
            "readTokenURI" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "tokenAddress" : {
                            "tag" : "scalar",
                            "name" : "string"
                        },
                        "tokenId" : {
                            "tag" : "scalar",
                            "name" : "i16"
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    ]
                }
            }
        }
    }
}
    );
}
      
// Functions
 

export function testingNft(
    tokenAddress: string,
    tokenId: number,
    config?: {ttl?: number}
): Promise<string>;

export function testingNft(
    peer: FluencePeer,
    tokenAddress: string,
    tokenId: number,
    config?: {ttl?: number}
): Promise<string>;

export function testingNft(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (seq
                          (seq
                           (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                           (call %init_peer_id% ("getDataSrv" "tokenAddress") [] tokenAddress)
                          )
                          (call %init_peer_id% ("getDataSrv" "tokenId") [] tokenId)
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (call "12D3KooWFEwNWcHqi9rtsmDhsYcDbRUCDXH84RC4FW6UfsFWaoHi" ("op" "noop") [])
                       )
                       (xor
                        (seq
                         (seq
                          (call "12D3KooWBNQ9SsBSBE9TD5nzFVF6Y8XmkfqGi8aAD8MedeQh4dDb" ("imageGenerator" "readTokenURI") [tokenAddress tokenId] res)
                          (call "12D3KooWFEwNWcHqi9rtsmDhsYcDbRUCDXH84RC4FW6UfsFWaoHi" ("op" "noop") [])
                         )
                         (call -relay- ("op" "noop") [])
                        )
                        (seq
                         (seq
                          (call "12D3KooWFEwNWcHqi9rtsmDhsYcDbRUCDXH84RC4FW6UfsFWaoHi" ("op" "noop") [])
                          (call -relay- ("op" "noop") [])
                         )
                         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [res])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                    )
    `
    return callFunction(
        args,
        {
    "functionName" : "testingNft",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                "tokenAddress" : {
                    "tag" : "scalar",
                    "name" : "string"
                },
                "tokenId" : {
                    "tag" : "scalar",
                    "name" : "i16"
                }
            }
        },
        "codomain" : {
            "tag" : "unlabeledProduct",
            "items" : [
                {
                    "tag" : "scalar",
                    "name" : "string"
                }
            ]
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}
